# Generated by Django 5.2.17 on 2026-09-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id_deporte', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
