# Generated by Django 5.2.17 on 2026-10-01 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_horario_materia_dictadomateria'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoDeportivo',
            fields=[
                ('id_grupo', models.BigAutoField(primary_key=True, serialize=False)),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='sports.deporte')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_deportivos', to='academic.horario')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_deportivos', to='academic.niveleducativo')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_deportivos', to='academic.profesor')),
            ],
        ),
    ]
