# Generated by Django 5.2.17 on 2026-10-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_grupodeportivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupodeportivo',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
