# Generated by Django 5.2.17 on 2026-10-01 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_horario_materia_dictadomateria'),
        ('sports', '0003_grupodeportivo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionDeporte',
            fields=[
                ('id_inscripcion', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones_deportivas', to='academic.alumno')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='sports.grupodeportivo')),
            ],
        ),
    ]
