# Generated by Django 5.2.17 on 2026-10-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_horario_materia_dictadomateria'),
        ('sports', '0004_inscripciondeporte'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='grupodeportivo',
            constraint=models.UniqueConstraint(fields=('deporte', 'nivel', 'profesor', 'horario'), name='grupo_deportivo_unico'),
        ),
    ]
