# Generated by Django 5.2.17 on 2026-10-07 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_tutoralumno'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratacionTransporte',
            fields=[
                ('id_contratacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('anio', models.PositiveSmallIntegerField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrataciones_transporte', to='academic.alumno')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrataciones', to='services.rutatransporte')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('alumno', 'mes', 'anio'), name='transporte_alumno_periodo_unico')],
            },
        ),
    ]
