# Generated by Django 5.2.17 on 2026-10-07 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_tutoralumno'),
        ('services', '0002_contrataciontransporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioComedor',
            fields=[
                ('id_servicio_comedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('valor_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContratacionComedor',
            fields=[
                ('id_contratacion_comedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('anio', models.PositiveSmallIntegerField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrataciones_comedor', to='academic.alumno')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrataciones', to='services.serviciocomedor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('alumno', 'mes', 'anio'), name='comedor_alumno_periodo_unico')],
            },
        ),
    ]
