# Generated by Django 5.2.17 on 2026-09-14 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id_perfil', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('DOCENTE', 'Docente'), ('ALUMNO', 'Alumno'), ('TUTOR', 'Padre / Tutor')], max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
