# Generated by Django 5.2.17 on 2026-09-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id_nivel', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
