# Generated by Django 5.2.17 on 2026-09-16 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.BigAutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DictadoMateria',
            fields=[
                ('id_dictado', models.BigAutoField(primary_key=True, serialize=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dictados', to='academic.curso')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dictados', to='academic.profesor')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dictados', to='academic.horario')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dictados', to='academic.materia')),
            ],
        ),
    ]
