# Generated by Django 5.2.17 on 2026-10-05 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorAlumno',
            fields=[
                ('id_relacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutores_asociados', to='academic.alumno')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos_asociados', to='academic.tutor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tutor', 'alumno'), name='tutor_alumno_unico')],
            },
        ),
    ]
